package StudentManagementSystem;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import java.awt.*;
import java.awt.event.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;

public class EnrollmentPageFrame extends JFrame {
    private JTextField enrollIdField, enrollDateField, gradeField;
    private JComboBox<Student> studentCombo;
    private JComboBox<Course> courseCombo;
    private DefaultTableModel tableModel;
    private EnrollmentDAO enrollmentDAO = new EnrollmentDAO();
    private StudentDAO studentDAO = new StudentDAO();
    private CourseDAO courseDAO = new CourseDAO();

    public EnrollmentPageFrame() {
        setTitle("Student Information Management System - Enrollment");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1070, 600);
        setLocationRelativeTo(null);
        setLayout(null);

        // Top bar with title and back arrow
        JPanel topPanel = new JPanel(null);
        topPanel.setBackground(new Color(70, 130, 180));
        topPanel.setBounds(0, 0, 1070, 60);

        JButton backButton = new JButton();
        backButton.setBounds(10, 10, 30, 30);
        backButton.setBackground(new Color(255, 0, 0));
        backButton.setBorderPainted(false);
        backButton.setFocusPainted(false);
        backButton.setIcon(new ImageIcon(
                new ImageIcon("src/images/back_arrow.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        backButton.addActionListener(e -> {
            dispose();
            new HomePageFrame();
        });

        JLabel titleLabel = new JLabel("Student Information Management Svstem", JLabel.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setBounds(60, 10, 950, 40);

        topPanel.add(backButton);
        topPanel.add(titleLabel);

        // Left form panel
        JPanel formPanel = new JPanel();
        formPanel.setLayout(null);
        formPanel.setBackground(new Color(210, 225, 245));
        formPanel.setBounds(0, 60, 420, 500);

        enrollIdField = new JTextField();
        // enroll_id is auto-generated by DB: make the field read-only / non-editable
        enrollIdField.setEditable(false);
        enrollIdField.setToolTipText("Auto-generated by database");
        enrollIdField.setFocusable(false);
        enrollIdField.setBackground(new Color(240, 240, 240));
        enrollDateField = new JTextField();
        // make enrollDateField open calendar on click
        enrollDateField.setEditable(false);
        enrollDateField.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        enrollDateField.setToolTipText("Click to select date");
        enrollDateField.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Window win = SwingUtilities.getWindowAncestor(enrollDateField);
                Frame owner = (win instanceof Frame) ? (Frame) win : null;
                Date initial = null;
                String txt = enrollDateField.getText().trim();
                if (!txt.isEmpty()) {
                    try {
                        initial = new SimpleDateFormat("yyyy-MM-dd").parse(txt);
                    } catch (ParseException ex) {
                        initial = new Date();
                    }
                } else {
                    initial = new Date();
                }
                DatePickerDialog picker = new DatePickerDialog(owner, initial);
                picker.setLocationRelativeTo(enrollDateField);
                picker.setVisible(true);
                Date picked = picker.getSelectedDate();
                if (picked != null) {
                    enrollDateField.setText(new SimpleDateFormat("yyyy-MM-dd").format(picked));
                }
            }
        });

        gradeField = new JTextField();

        // Student dropdown (stores Student objects, shows "id - name")
        studentCombo = new JComboBox<>();
        for (Student s : studentDAO.getAllStudents())
            studentCombo.addItem(s);
        studentCombo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Student) {
                    Student st = (Student) value;
                    setText(st.getStudentId() + " - " + st.getName());
                } else {
                    setText(value == null ? "" : value.toString());
                }
                return this;
            }
        });
        studentCombo.setMaximumRowCount(10);

        // Course dropdown (stores Course objects, shows "id - name")
        courseCombo = new JComboBox<>();
        for (Course c : courseDAO.getAllCourses())
            courseCombo.addItem(c);
        courseCombo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Course) {
                    Course co = (Course) value;
                    setText(co.getCourseId() + " - " + co.getCourseName());
                } else {
                    setText(value == null ? "" : value.toString());
                }
                return this;
            }
        });
        courseCombo.setMaximumRowCount(10);

        String[] labels = {"Enroll ID", "Student ID", "Course ID", "Enroll Date", "Grade"};
        JTextField[] fields = { enrollIdField, null, null, enrollDateField, gradeField };
        int y = 30;
        for (int i = 0; i < labels.length; i++) {
            // use JLabel so the text remains white (disabled JButton shows gray)
            JLabel lbl = new JLabel(labels[i], SwingConstants.LEFT);
            lbl.setBounds(20, y, 150, 35);
            lbl.setOpaque(true);
            lbl.setBackground(new Color(70, 130, 180));
            lbl.setForeground(Color.WHITE);
            lbl.setFont(new Font("Arial", Font.BOLD, 14));
            lbl.setBorder(BorderFactory.createEmptyBorder(0, 8, 0, 0));
            formPanel.add(lbl);

            if (labels[i].equals("Student ID")) {
                studentCombo.setBounds(180, y, 210, 35);
                formPanel.add(studentCombo);
            } else if (labels[i].equals("Course ID")) {
                courseCombo.setBounds(180, y, 210, 35);
                formPanel.add(courseCombo);
            } else {
                fields[i].setBounds(180, y, 210, 35);
                fields[i].setFont(new Font("Arial", Font.PLAIN, 14));
                formPanel.add(fields[i]);
            }
            y += 45;
        }

        // Action buttons
        JButton addBtn = new JButton("Add");
        addBtn.setBounds(50, 300, 90, 40);
        addBtn.setBackground(new Color(25, 25, 112));
        addBtn.setForeground(Color.WHITE);
        addBtn.setFont(new Font("Arial", Font.BOLD, 14));
        formPanel.add(addBtn);

        JButton updateBtn = new JButton("Update");
        updateBtn.setBounds(160, 300, 90, 40);
        updateBtn.setBackground(new Color(25, 25, 112));
        updateBtn.setForeground(Color.WHITE);
        updateBtn.setFont(new Font("Arial", Font.BOLD, 14));
        formPanel.add(updateBtn);


        JButton clearBtn = new JButton("Clear");
        clearBtn.setBounds(270, 300, 90, 40);
        clearBtn.setBackground(new Color(25, 25, 112));
        clearBtn.setForeground(Color.WHITE);
        clearBtn.setFont(new Font("Arial", Font.BOLD, 14));
        formPanel.add(clearBtn);

        // Search bar
        JLabel searchByLabel = new JLabel("Search By");
        searchByLabel.setFont(new Font("Arial", Font.BOLD, 14));
        searchByLabel.setBounds(450, 70, 80, 30);

        JTextField searchField = new JTextField();
        searchField.setBounds(540, 70, 200, 30);

        JButton searchBtn = new JButton("Search");
        searchBtn.setBounds(750, 70, 90, 30);
        searchBtn.setBackground(new Color(25, 25, 112));
        searchBtn.setForeground(Color.WHITE);

        JButton clearSearchBtn = new JButton("Clear");
        clearSearchBtn.setBounds(850, 70, 90, 30);
        clearSearchBtn.setBackground(new Color(25, 25, 112));
        clearSearchBtn.setForeground(Color.WHITE);

        // Table
        String[] tableHeaders = {"Enroll ID", "Student ID", "Course ID", "Enroll Date", "Grade"};
        tableModel = new DefaultTableModel(tableHeaders, 0);
        JTable enrollTable = new JTable(tableModel);
        JScrollPane tableScroll = new JScrollPane(enrollTable);
        tableScroll.setBounds(450, 110, 590, 450);

        // Add components to frame
        add(topPanel);
        add(formPanel);
        add(searchByLabel);
        add(searchField);
        add(searchBtn);
        add(clearSearchBtn);
        add(tableScroll);

        // Add button logic
        // Add: do NOT require enrollId (DB generates it)
        addBtn.addActionListener(e -> {
            Student selStudent = (Student) studentCombo.getSelectedItem();
            Course selCourse = (Course) courseCombo.getSelectedItem();
            if (selStudent == null || selCourse == null) {
                JOptionPane.showMessageDialog(this, "Select student and course.", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            String enrollDate = enrollDateField.getText().trim();
            String grade = gradeField.getText().trim();
            if (enrollDate.isEmpty() || grade.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields!", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            // date format validation (yyyy-MM-dd)
            if (!enrollDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(this, "Enroll Date must be in YYYY-MM-DD format.", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            int studentId = selStudent.getStudentId();
            int courseId = selCourse.getCourseId();
            Enrollment enroll = new Enrollment(0, studentId, courseId, enrollDate, grade);
            boolean success = enrollmentDAO.addEnrollment(enroll);
            if (success) {
                enrollIdField.setText(String.valueOf(enroll.getEnrollId()));
                JOptionPane.showMessageDialog(this, "Enrollment added successfully! ID: " + enroll.getEnrollId(),
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadEnrollments();
                studentCombo.setSelectedIndex(-1);
                courseCombo.setSelectedIndex(-1);
                enrollDateField.setText("");
                gradeField.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add enrollment!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // Update: update selected/filled enrollment row
        updateBtn.addActionListener(e -> {
            String idText = enrollIdField.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Select an enrollment row to update.", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            int enrollId;
            try {
                enrollId = Integer.parseInt(idText);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Enroll ID is invalid.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Student selStudent = (Student) studentCombo.getSelectedItem();
            Course selCourse = (Course) courseCombo.getSelectedItem();
            if (selStudent == null || selCourse == null) {
                JOptionPane.showMessageDialog(this, "Select student and course.", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            String enrollDate = enrollDateField.getText().trim();
            String grade = gradeField.getText().trim();
            if (enrollDate.isEmpty() || grade.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all fields!", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!enrollDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(this, "Enroll Date must be in YYYY-MM-DD format.", "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            int studentId = selStudent.getStudentId();
            int courseId = selCourse.getCourseId();
            Enrollment enroll = new Enrollment(enrollId, studentId, courseId, enrollDate, grade);
            boolean ok = enrollmentDAO.updateEnrollment(enroll);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Enrollment updated", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadEnrollments();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Update failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        clearBtn.addActionListener(e -> clearFields());

        // Search button logic
        searchBtn.addActionListener(e -> {
            String keyword = searchField.getText().trim();
            tableModel.setRowCount(0);
            for (Enrollment enroll : enrollmentDAO.searchEnrollments(keyword)) {
                tableModel.addRow(new Object[] {
                        enroll.getEnrollId(),
                        enroll.getStudentId(),
                        enroll.getCourseId(),
                        enroll.getEnrollDate(),
                        enroll.getGrade()
                });
            }
        });

        // Clear search button logic
        clearSearchBtn.addActionListener(e -> {
            searchField.setText("");
            loadEnrollments();
        });

        // popup menu
        JPopupMenu popup = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Delete");
        JMenuItem updateItem = new JMenuItem("Update");
        popup.add(deleteItem);
        popup.add(updateItem);

        enrollTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                int row = enrollTable.rowAtPoint(e.getPoint());
                if (row >= 0) {
                    enrollTable.getSelectionModel().setSelectionInterval(row, row);
                    if (SwingUtilities.isRightMouseButton(e)) {
                        popup.show(enrollTable, e.getX(), e.getY());
                    }
                }
            }
        });

        deleteItem.addActionListener(e -> {
            int row = enrollTable.getSelectedRow();
            if (row >= 0) {
                int id = (int) tableModel.getValueAt(row, 0);
                int confirm = JOptionPane.showConfirmDialog(this, "Delete this enrollment?", "Confirm",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    boolean ok = enrollmentDAO.deleteEnrollment(id);
                    if (ok) {
                        JOptionPane.showMessageDialog(this, "Deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
                        loadEnrollments();
                        clearFields();
                    } else {
                        JOptionPane.showMessageDialog(this, "Delete failed", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });

        updateItem.addActionListener(e -> {
            int row = enrollTable.getSelectedRow();
            if (row >= 0) {
                enrollIdField.setText(tableModel.getValueAt(row, 0).toString());
                // select matching student in combo
                try {
                    int sid = Integer.parseInt(tableModel.getValueAt(row, 1).toString());
                    boolean found = false;
                    for (int i = 0; i < studentCombo.getItemCount(); i++) {
                        Student s = studentCombo.getItemAt(i);
                        if (s != null && s.getStudentId() == sid) {
                            studentCombo.setSelectedIndex(i);
                            found = true;
                            break;
                        }
                    }
                    if (!found)
                        studentCombo.setSelectedIndex(-1);
                } catch (Exception ex) {
                    studentCombo.setSelectedIndex(-1);
                }
                // select matching course in combo
                try {
                    int cid = Integer.parseInt(tableModel.getValueAt(row, 2).toString());
                    boolean found2 = false;
                    for (int i = 0; i < courseCombo.getItemCount(); i++) {
                        Course c = courseCombo.getItemAt(i);
                        if (c != null && c.getCourseId() == cid) {
                            courseCombo.setSelectedIndex(i);
                            found2 = true;
                            break;
                        }
                    }
                    if (!found2)
                        courseCombo.setSelectedIndex(-1);
                } catch (Exception ex) {
                    courseCombo.setSelectedIndex(-1);
                }
                enrollDateField.setText(tableModel.getValueAt(row, 3).toString());
                gradeField.setText(tableModel.getValueAt(row, 4).toString());
                enrollIdField.setEditable(false);
            }
        });
        loadEnrollments();
        setVisible(true);
    }

    private void loadEnrollments() {
        tableModel.setRowCount(0);
        for (Enrollment enroll : enrollmentDAO.getAllEnrollments()) {
            tableModel.addRow(new Object[]{
                enroll.getEnrollId(),
                enroll.getStudentId(),
                enroll.getCourseId(),
                enroll.getEnrollDate(),
                enroll.getGrade()
            });
        }
    }

    private void clearFields() {
        // clear inputs; enroll_id remains non-editable and cleared for a fresh add
        enrollIdField.setText("");
        studentCombo.setSelectedIndex(-1);
        courseCombo.setSelectedIndex(-1);
        enrollDateField.setText("");
        gradeField.setText("");
        // allow entering new record id not editable (DB will generate), reset editable
        // state
        enrollIdField.setEditable(false);
    }
}